Shader "Hidden/Internal-ODSWorldTexture" {
	Properties {
		_MainTex ("", 2D) = "white" {}
		_Cutoff ("", Float) = 0.5
		_Color ("", Vector) = (1,1,1,1)
	}
	SubShader {
		Tags { "RenderType" = "Opaque" }
		Pass {
			Tags { "RenderType" = "Opaque" }
			GpuProgramID 62904
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float       
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb0[1].xyzw
					mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyz, r0.xyzx, cb0[3].xyzx
					mad o1.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mul r0.xyzw, r1.yyyy, cb1[18].xyzw
					mad r0.xyzw, cb1[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb1[19].xyzw, r1.zzzz, r0.xyzw
					add o0.xyzw, r0.xyzw, cb1[20].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					mov o0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	SubShader {
		Tags { "RenderType" = "TransparentCutout" }
		Pass {
			Tags { "RenderType" = "TransparentCutout" }
			GpuProgramID 66522
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// NORMAL                   0   xyz         1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xy          2     NONE   float   xy  
					//
					vs_4_0
					dcl_constantbuffer CB0[3], immediateIndexed
					dcl_constantbuffer CB1[4], immediateIndexed
					dcl_constantbuffer CB2[21], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v2.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_temps 2
					mul r0.xyzw, v0.yyyy, cb1[1].xyzw
					mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
					mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
					add r1.xyz, r0.xyzx, cb1[3].xyzx
					mad o1.xyzw, cb1[3].xyzw, v0.wwww, r0.xyzw
					mul r0.xyzw, r1.yyyy, cb2[18].xyzw
					mad r0.xyzw, cb2[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb2[19].xyzw, r1.zzzz, r0.xyzw
					add o0.xyzw, r0.xyzw, cb2[20].xyzw
					mad o2.xy, v2.xyxx, cb0[2].xyxx, cb0[2].zwzz
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 1   xy          2     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xyzw
					dcl_input_ps linear v2.xy
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mad r0.x, r0.w, cb0[4].w, -cb0[3].x
					lt r0.x, r0.x, l(0.000000)
					discard_nz r0.x
					mov o0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	SubShader {
		Tags { "RenderType" = "TreeBark" }
		Pass {
			Tags { "RenderType" = "TreeBark" }
			GpuProgramID 157769
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TANGENT                  0   xyzw        1     NONE   float       
					// NORMAL                   0   xyz         2     NONE   float   x z 
					// TEXCOORD                 0   xyzw        3     NONE   float       
					// TEXCOORD                 1   xyzw        4     NONE   float   xy  
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[4], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_constantbuffer CB4[13], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.xz
					dcl_input v4.xy
					dcl_input v7.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 4
					dp3 r0.x, cb2[3].xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					add r0.y, r0.x, v7.x
					add r0.z, r0.y, v7.y
					mul r1.xyz, v0.xyzx, cb4[6].xyzx
					dp3 r0.x, r1.xyzx, r0.zzzz
					add r0.xyzw, r0.xxyy, cb1[0].yyyy
					mul r0.xyzw, r0.xyzw, l(1.975000, 0.793000, 0.375000, 0.193000)
					frc r0.xyzw, r0.xyzw
					mad r0.xyzw, r0.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-0.500000, -0.500000, -0.500000, -0.500000)
					frc r0.xyzw, r0.xyzw
					mad r0.xyzw, r0.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
					mul r2.xyzw, |r0.xyzw|, |r0.xyzw|
					mad r0.xyzw, -|r0.xyzw|, l(2.000000, 2.000000, 2.000000, 2.000000), l(3.000000, 3.000000, 3.000000, 3.000000)
					mul r0.xyzw, r0.xyzw, r2.xyzw
					add r0.xy, r0.ywyy, r0.xzxx
					mul r2.xyz, r0.yyyy, cb0[4].xyzx
					mul r2.xyz, r2.xyzx, v4.yyyy
					mul r3.y, r0.y, v4.y
					mul r0.y, v7.y, l(0.100000)
					mul r3.xz, r0.yyyy, v2.xxzx
					mov r0.z, l(0.300000)
					mad r0.xyz, r0.xzxx, r3.xyzx, r2.xyzx
					mad r0.xyz, r0.xyzx, cb0[4].wwww, r1.xyzx
					mad r0.xyz, v4.xxxx, cb0[4].xyzx, r0.xyzx
					dp3 r0.w, cb4[11].xyzx, r0.xyzx
					add r0.w, r0.w, cb4[11].w
					mad r1.xyz, -r0.wwww, cb4[11].xyzx, r0.xyzx
					add r0.xyz, r0.xyzx, -r1.xyzx
					mad r0.xyz, cb4[12].xxxx, r0.xyzx, r1.xyzx
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r0.xyzw, cb2[2].xyzw, r0.zzzz, r1.xyzw
					add r0.xyzw, r0.xyzw, cb2[3].xyzw
					mul r1.xyzw, r0.yyyy, cb3[18].xyzw
					mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
					mov o1.xyzw, r0.xyzw
					add o0.xyzw, r1.xyzw, cb3[20].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					mov o0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	SubShader {
		Tags { "RenderType" = "TreeLeaf" }
		Pass {
			Tags { "RenderType" = "TreeLeaf" }
			GpuProgramID 211170
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// TANGENT                  0   xyzw        1     NONE   float      w
					// NORMAL                   0   xyz         2     NONE   float   xyz 
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float   xy  
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[5], immediateIndexed
					dcl_constantbuffer CB1[1], immediateIndexed
					dcl_constantbuffer CB2[8], immediateIndexed
					dcl_constantbuffer CB3[21], immediateIndexed
					dcl_constantbuffer CB4[13], immediateIndexed
					dcl_input v0.xyz
					dcl_input v1.w
					dcl_input v2.xyz
					dcl_input v3.xy
					dcl_input v4.xy
					dcl_input v7.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 4
					mul r0.xyzw, cb2[5].xyzw, cb3[14].yyyy
					mad r0.xyzw, cb2[4].xyzw, cb3[14].xxxx, r0.xyzw
					mad r0.xyzw, cb2[6].xyzw, cb3[14].zzzz, r0.xyzw
					mad r0.xyzw, cb2[7].xyzw, cb3[14].wwww, r0.xyzw
					mul r0.xyzw, r0.xyzw, v2.yyyy
					mul r1.xyzw, cb2[5].xyzw, cb3[13].yyyy
					mad r1.xyzw, cb2[4].xyzw, cb3[13].xxxx, r1.xyzw
					mad r1.xyzw, cb2[6].xyzw, cb3[13].zzzz, r1.xyzw
					mad r1.xyzw, cb2[7].xyzw, cb3[13].wwww, r1.xyzw
					mad r0.xyzw, v2.xxxx, r1.xyzw, r0.xyzw
					mul r1.xyzw, cb2[5].xyzw, cb3[15].yyyy
					mad r1.xyzw, cb2[4].xyzw, cb3[15].xxxx, r1.xyzw
					mad r1.xyzw, cb2[6].xyzw, cb3[15].zzzz, r1.xyzw
					mad r1.xyzw, cb2[7].xyzw, cb3[15].wwww, r1.xyzw
					mad r1.xyzw, v2.zzzz, r1.xyzw, r0.xyzw
					dp4 r0.w, r1.xyzw, r1.xyzw
					rsq r0.w, r0.w
					mad r1.xy, r1.xzxx, r0.wwww, -v2.xzxx
					add r0.w, -|v1.w|, l(1.000000)
					mad r1.xy, r0.wwww, r1.xyxx, v2.xzxx
					mad r0.xyz, r0.xyzx, r0.wwww, v0.xyzx
					mul r0.xyz, r0.xyzx, cb4[6].xyzx
					mul r0.w, v7.y, l(0.100000)
					mul r1.xz, r1.xxyx, r0.wwww
					dp3 r0.w, cb2[3].xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
					add r2.y, r0.w, v7.x
					add r0.w, r2.y, v7.y
					dp3 r2.x, r0.xyzx, r0.wwww
					add r2.xyzw, r2.xxyy, cb1[0].yyyy
					mul r2.xyzw, r2.xyzw, l(1.975000, 0.793000, 0.375000, 0.193000)
					frc r2.xyzw, r2.xyzw
					mad r2.xyzw, r2.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-0.500000, -0.500000, -0.500000, -0.500000)
					frc r2.xyzw, r2.xyzw
					mad r2.xyzw, r2.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
					mul r3.xyzw, |r2.xyzw|, |r2.xyzw|
					mad r2.xyzw, -|r2.xyzw|, l(2.000000, 2.000000, 2.000000, 2.000000), l(3.000000, 3.000000, 3.000000, 3.000000)
					mul r2.xyzw, r2.xyzw, r3.xyzw
					add r2.xy, r2.ywyy, r2.xzxx
					mul r3.xyz, r2.yyyy, cb0[4].xyzx
					mul r3.xyz, r3.xyzx, v4.yyyy
					mul r1.y, r2.y, v4.y
					mov r2.z, l(0.300000)
					mad r1.xyz, r2.xzxx, r1.xyzx, r3.xyzx
					mad r0.xyz, r1.xyzx, cb0[4].wwww, r0.xyzx
					mad r0.xyz, v4.xxxx, cb0[4].xyzx, r0.xyzx
					dp3 r0.w, cb4[11].xyzx, r0.xyzx
					add r0.w, r0.w, cb4[11].w
					mad r1.xyz, -r0.wwww, cb4[11].xyzx, r0.xyzx
					add r0.xyz, r0.xyzx, -r1.xyzx
					mad r0.xyz, cb4[12].xxxx, r0.xyzx, r1.xyzx
					mul r1.xyzw, r0.yyyy, cb2[1].xyzw
					mad r1.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
					mad r0.xyzw, cb2[2].xyzw, r0.zzzz, r1.xyzw
					add r0.xyzw, r0.xyzw, cb2[3].xyzw
					mul r1.xyzw, r0.yyyy, cb3[18].xyzw
					mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
					mov o2.xyzw, r0.xyzw
					add o0.xyzw, r1.xyzw, cb3[20].xyzw
					mov o1.xy, v3.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[8], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyzw
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					add r0.x, r0.w, -cb0[7].y
					lt r0.x, r0.x, l(0.000000)
					discard_nz r0.x
					mov o0.xyzw, v2.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	SubShader {
		Tags { "DisableBatching" = "true" "RenderType" = "TreeOpaque" }
		Pass {
			Tags { "DisableBatching" = "true" "RenderType" = "TreeOpaque" }
			GpuProgramID 303200
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyz         1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float      w
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[13], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.w
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_temps 2
					mul r0.xyz, v0.xyzx, cb2[6].xyzx
					mul r1.xyz, r0.yyyy, cb2[8].xyzx
					mad r1.xyz, cb2[7].xyzx, r0.xxxx, r1.xyzx
					mad r1.xyz, cb2[9].xyzx, r0.zzzz, r1.xyzx
					mad r1.xyz, -v0.xyzx, cb2[6].xyzx, r1.xyzx
					mad r0.xyz, v2.wwww, r1.xyzx, r0.xyzx
					dp3 r0.w, cb2[11].xyzx, r0.xyzx
					add r0.w, r0.w, cb2[11].w
					mad r1.xyz, -r0.wwww, cb2[11].xyzx, r0.xyzx
					add r0.xyz, r0.xyzx, -r1.xyzx
					mad r0.xyz, cb2[12].xxxx, r0.xyzx, r1.xyzx
					mul r1.xyzw, r0.yyyy, cb0[1].xyzw
					mad r1.xyzw, cb0[0].xyzw, r0.xxxx, r1.xyzw
					mad r0.xyzw, cb0[2].xyzw, r0.zzzz, r1.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mov o1.xyzw, r0.xyzw
					add o0.xyzw, r1.xyzw, cb1[20].xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xyzw        1     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_input_ps linear v1.xyzw
					dcl_output o0.xyzw
					mov o0.xyzw, v1.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	SubShader {
		Tags { "DisableBatching" = "true" "RenderType" = "TreeTransparentCutout" }
		Pass {
			Tags { "DisableBatching" = "true" "RenderType" = "TreeTransparentCutout" }
			GpuProgramID 330159
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyz         1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float      w
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[13], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.w
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyz, v0.xyzx, cb2[6].xyzx
					mul r1.xyz, r0.yyyy, cb2[8].xyzx
					mad r1.xyz, cb2[7].xyzx, r0.xxxx, r1.xyzx
					mad r1.xyz, cb2[9].xyzx, r0.zzzz, r1.xyzx
					mad r1.xyz, -v0.xyzx, cb2[6].xyzx, r1.xyzx
					mad r0.xyz, v2.wwww, r1.xyzx, r0.xyzx
					dp3 r0.w, cb2[11].xyzx, r0.xyzx
					add r0.w, r0.w, cb2[11].w
					mad r1.xyz, -r0.wwww, cb2[11].xyzx, r0.xyzx
					add r0.xyz, r0.xyzx, -r1.xyzx
					mad r0.xyz, cb2[12].xxxx, r0.xyzx, r1.xyzx
					mul r1.xyzw, r0.yyyy, cb0[1].xyzw
					mad r1.xyzw, cb0[0].xyzw, r0.xxxx, r1.xyzw
					mad r0.xyzw, cb0[2].xyzw, r0.zzzz, r1.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mov o2.xyzw, r0.xyzw
					add o0.xyzw, r1.xyzw, cb1[20].xyzw
					mov o1.xy, v3.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyzw
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					add r0.x, r0.w, -cb0[3].x
					lt r0.x, r0.x, l(0.000000)
					discard_nz r0.x
					mov o0.xyzw, v2.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
		Pass {
			Tags { "DisableBatching" = "true" "RenderType" = "TreeTransparentCutout" }
			Cull Front
			GpuProgramID 457754
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyz 
					// NORMAL                   0   xyz         1     NONE   float       
					// COLOR                    0   xyzw        2     NONE   float      w
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[13], immediateIndexed
					dcl_input v0.xyz
					dcl_input v2.w
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 2
					mul r0.xyz, v0.xyzx, cb2[6].xyzx
					mul r1.xyz, r0.yyyy, cb2[8].xyzx
					mad r1.xyz, cb2[7].xyzx, r0.xxxx, r1.xyzx
					mad r1.xyz, cb2[9].xyzx, r0.zzzz, r1.xyzx
					mad r1.xyz, -v0.xyzx, cb2[6].xyzx, r1.xyzx
					mad r0.xyz, v2.wwww, r1.xyzx, r0.xyzx
					dp3 r0.w, cb2[11].xyzx, r0.xyzx
					add r0.w, r0.w, cb2[11].w
					mad r1.xyz, -r0.wwww, cb2[11].xyzx, r0.xyzx
					add r0.xyz, r0.xyzx, -r1.xyzx
					mad r0.xyz, cb2[12].xxxx, r0.xyzx, r1.xyzx
					mul r1.xyzw, r0.yyyy, cb0[1].xyzw
					mad r1.xyzw, cb0[0].xyzw, r0.xxxx, r1.xyzw
					mad r0.xyzw, cb0[2].xyzw, r0.zzzz, r1.xyzw
					add r0.xyzw, r0.xyzw, cb0[3].xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					mov o2.xyzw, r0.xyzw
					add o0.xyzw, r1.xyzw, cb1[20].xyzw
					mov o1.xy, v3.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyzw
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					add r0.x, r0.w, -cb0[3].x
					lt r0.x, r0.x, l(0.000000)
					discard_nz r0.x
					mov o0.xyzw, v2.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	SubShader {
		Tags { "RenderType" = "TreeBillboard" }
		Pass {
			Tags { "RenderType" = "TreeBillboard" }
			Cull Off
			GpuProgramID 490650
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float       
					// TEXCOORD                 0   xyzw        2     NONE   float   xy  
					// TEXCOORD                 1   xy          3     NONE   float   xy  
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[17], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v2.xy
					dcl_input v3.xy
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xy
					dcl_output o2.xyzw
					dcl_temps 2
					add r0.xyz, v0.xyzx, -cb2[15].xyzx
					dp3 r0.x, r0.xyzx, r0.xyzx
					lt r0.x, cb2[16].x, r0.x
					mov r1.xy, v3.xyxx
					mov r1.z, v2.y
					movc r0.xyz, r0.xxxx, l(0,0,0,0), r1.xyzx
					add r0.z, -r0.y, r0.z
					mad r0.y, cb2[15].w, r0.z, r0.y
					mad r1.xyz, cb2[12].yzwy, r0.xxxx, v0.xyzx
					mul r0.xzw, |r0.xxxx|, cb2[14].xxyz
					mad r1.xyz, cb2[13].xyzx, r0.yyyy, r1.xyzx
					mad r0.xyz, r0.xzwx, cb2[13].wwww, r1.xyzx
					mul r1.xyzw, r0.yyyy, cb0[1].xyzw
					mad r1.xyzw, cb0[0].xyzw, r0.xxxx, r1.xyzw
					mad r0.xyzw, cb0[2].xyzw, r0.zzzz, r1.xyzw
					add r1.xyz, r0.xyzx, cb0[3].xyzx
					mad o2.xyzw, cb0[3].xyzw, v0.wwww, r0.xyzw
					mul r0.xyzw, r1.yyyy, cb1[18].xyzw
					mad r0.xyzw, cb1[17].xyzw, r1.xxxx, r0.xyzw
					mad r0.xyzw, cb1[19].xyzw, r1.zzzz, r0.xyzw
					add o0.xyzw, r0.xyzw, cb1[20].xyzw
					lt r0.x, l(0.000000), v2.y
					and o1.y, r0.x, l(0x3f800000)
					mov o1.x, v2.x
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// TEXCOORD                 0   xy          1     NONE   float   xy  
					// TEXCOORD                 1   xyzw        2     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.xy
					dcl_input_ps linear v2.xyzw
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v1.xyxx, t0.xyzw, s0
					add r0.x, r0.w, l(-0.001000)
					lt r0.x, r0.x, l(0.000000)
					discard_nz r0.x
					mov o0.xyzw, v2.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	SubShader {
		Tags { "RenderType" = "GrassBillboard" }
		Pass {
			Tags { "RenderType" = "GrassBillboard" }
			Cull Off
			GpuProgramID 553361
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TANGENT                  0   xyzw        1     NONE   float   xy  
					// NORMAL                   0   xyz         2     NONE   float       
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float       
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float   xyz 
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[5], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v1.xy
					dcl_input v3.xy
					dcl_input v7.xyz
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o3.xyzw
					dcl_temps 4
					add r0.xyz, v0.xyzx, -cb2[2].xyzx
					dp3 r0.x, r0.xyzx, r0.xyzx
					lt r0.x, cb2[1].w, r0.x
					movc r0.xy, r0.xxxx, l(0,0,0,0), v1.xyxx
					mad r0.xzw, r0.xxxx, cb2[3].xxyz, v0.xxyz
					mad r0.xyz, r0.yyyy, cb2[4].xyzx, r0.xzwx
					mul r1.xy, r0.xzxx, cb2[1].yyyy
					mul r2.xyzw, r1.yyyy, l(0.006000, 0.020000, 0.020000, 0.050000)
					mad r1.xyzw, r1.xxxx, l(0.012000, 0.020000, 0.060000, 0.024000), r2.xyzw
					mad r1.xyzw, cb2[1].xxxx, l(1.200000, 2.000000, 1.600000, 4.800000), r1.xyzw
					frc r1.xyzw, r1.xyzw
					mad r1.xyzw, r1.xyzw, l(6.408849, 6.408849, 6.408849, 6.408849), l(-3.141593, -3.141593, -3.141593, -3.141593)
					mul r2.xyzw, r1.xyzw, r1.xyzw
					mul r3.xyzw, r1.xyzw, r2.xyzw
					mad r1.xyzw, r3.xyzw, l(-0.161616, -0.161616, -0.161616, -0.161616), r1.xyzw
					mul r3.xyzw, r2.xyzw, r3.xyzw
					mul r2.xyzw, r2.xyzw, r3.xyzw
					mad r1.xyzw, r3.xyzw, l(0.008333, 0.008333, 0.008333, 0.008333), r1.xyzw
					mad r1.xyzw, r2.xyzw, l(-0.000198, -0.000198, -0.000198, -0.000198), r1.xyzw
					mul r1.xyzw, r1.xyzw, r1.xyzw
					mul r1.xyzw, r1.xyzw, r1.xyzw
					mul r2.xyzw, r1.xyzw, v1.yyyy
					dp4 r0.w, r1.xyzw, l(0.674200, 0.674200, 0.269680, 0.134840)
					mul r0.w, r0.w, l(0.700000)
					dp4 r1.x, r2.xyzw, l(0.024000, 0.040000, -0.120000, 0.096000)
					dp4 r1.z, r2.xyzw, l(0.006000, 0.020000, -0.020000, 0.100000)
					mad r0.xz, -r1.xxzx, cb2[1].zzzz, r0.xxzx
					mul r1.xyzw, r0.yyyy, cb0[1].xyzw
					add r2.xyz, r0.xyzx, -cb2[2].xyzx
					dp3 r0.y, r2.xyzx, r2.xyzx
					add r0.y, -r0.y, cb2[1].w
					dp2_sat o1.w, cb2[2].wwww, r0.yyyy
					mad r1.xyzw, cb0[0].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb0[2].xyzw, r0.zzzz, r1.xyzw
					add r0.xyz, r1.xyzx, cb0[3].xyzx
					mad o3.xyzw, cb0[3].xyzw, v0.wwww, r1.xyzw
					mul r1.xyzw, r0.yyyy, cb1[18].xyzw
					mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
					mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
					add o0.xyzw, r1.xyzw, cb1[20].xyzw
					add r0.xyz, cb2[0].xyzx, l(-0.500000, -0.500000, -0.500000, 0.000000)
					mad r0.xyz, r0.wwww, r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000)
					add r0.xyz, r0.xyzx, r0.xyzx
					mul o1.xyz, r0.xyzx, v7.xyzx
					mov o2.xy, v3.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.w
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v3.xyzw
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mad r0.x, r0.w, v1.w, -cb0[3].x
					lt r0.x, r0.x, l(0.000000)
					discard_nz r0.x
					mov o0.xyzw, v3.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
	SubShader {
		Tags { "RenderType" = "Grass" }
		Pass {
			Tags { "RenderType" = "Grass" }
			Cull Off
			GpuProgramID 649013
			Program "vp" {
				SubProgram "d3d11 " {
					"!!DX11VertexSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// POSITION                 0   xyzw        0     NONE   float   xyzw
					// TANGENT                  0   xyzw        1     NONE   float       
					// NORMAL                   0   xyz         2     NONE   float       
					// TEXCOORD                 0   xyzw        3     NONE   float   xy  
					// TEXCOORD                 1   xyzw        4     NONE   float       
					// TEXCOORD                 2   xyzw        5     NONE   float       
					// TEXCOORD                 3   xyzw        6     NONE   float       
					// COLOR                    0   xyzw        7     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float   xyzw
					// COLOR                    0   xyzw        1     NONE   float   xyzw
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
					//
					vs_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_constantbuffer CB1[21], immediateIndexed
					dcl_constantbuffer CB2[3], immediateIndexed
					dcl_input v0.xyzw
					dcl_input v3.xy
					dcl_input v7.xyzw
					dcl_output_siv o0.xyzw, position
					dcl_output o1.xyzw
					dcl_output o2.xy
					dcl_output o3.xyzw
					dcl_temps 3
					mul r0.xy, v0.xzxx, cb2[1].yyyy
					mul r1.xyzw, r0.yyyy, l(0.006000, 0.020000, 0.020000, 0.050000)
					mad r0.xyzw, r0.xxxx, l(0.012000, 0.020000, 0.060000, 0.024000), r1.xyzw
					mad r0.xyzw, cb2[1].xxxx, l(1.200000, 2.000000, 1.600000, 4.800000), r0.xyzw
					frc r0.xyzw, r0.xyzw
					mad r0.xyzw, r0.xyzw, l(6.408849, 6.408849, 6.408849, 6.408849), l(-3.141593, -3.141593, -3.141593, -3.141593)
					mul r1.xyzw, r0.xyzw, r0.xyzw
					mul r2.xyzw, r0.xyzw, r1.xyzw
					mad r0.xyzw, r2.xyzw, l(-0.161616, -0.161616, -0.161616, -0.161616), r0.xyzw
					mul r2.xyzw, r1.xyzw, r2.xyzw
					mul r1.xyzw, r1.xyzw, r2.xyzw
					mad r0.xyzw, r2.xyzw, l(0.008333, 0.008333, 0.008333, 0.008333), r0.xyzw
					mad r0.xyzw, r1.xyzw, l(-0.000198, -0.000198, -0.000198, -0.000198), r0.xyzw
					mul r0.xyzw, r0.xyzw, r0.xyzw
					mul r0.xyzw, r0.xyzw, r0.xyzw
					mul r1.x, v7.w, cb2[1].z
					mul r1.xyzw, r0.xyzw, r1.xxxx
					dp4 r0.x, r0.xyzw, l(0.674200, 0.674200, 0.269680, 0.134840)
					mul r0.x, r0.x, l(0.700000)
					dp4 r2.x, r1.xyzw, l(0.024000, 0.040000, -0.120000, 0.096000)
					dp4 r2.z, r1.xyzw, l(0.006000, 0.020000, -0.020000, 0.100000)
					mad r1.xz, -r2.xxzx, cb2[1].zzzz, v0.xxzx
					mul r2.xyzw, v0.yyyy, cb0[1].xyzw
					mad r2.xyzw, cb0[0].xyzw, r1.xxxx, r2.xyzw
					mad r2.xyzw, cb0[2].xyzw, r1.zzzz, r2.xyzw
					add r0.yzw, r2.xxyz, cb0[3].xxyz
					mad o3.xyzw, cb0[3].xyzw, v0.wwww, r2.xyzw
					mul r2.xyzw, r0.zzzz, cb1[18].xyzw
					mad r2.xyzw, cb1[17].xyzw, r0.yyyy, r2.xyzw
					mad r2.xyzw, cb1[19].xyzw, r0.wwww, r2.xyzw
					add o0.xyzw, r2.xyzw, cb1[20].xyzw
					mov r1.y, v0.y
					add r0.yzw, r1.xxyz, -cb2[2].xxyz
					dp3 r0.y, r0.yzwy, r0.yzwy
					add r0.y, -r0.y, cb2[1].w
					add r0.y, r0.y, r0.y
					mul_sat o1.w, r0.y, cb2[2].w
					add r0.yzw, cb2[0].xxyz, l(0.000000, -0.500000, -0.500000, -0.500000)
					mad r0.xyz, r0.xxxx, r0.yzwy, l(0.500000, 0.500000, 0.500000, 0.000000)
					mul r0.xyz, r0.xyzx, v7.xyzx
					add o1.xyz, r0.xyzx, r0.xyzx
					mov o2.xy, v3.xyxx
					ret 
					// Approximately 0 instruction slots used"
				}
			}
			Program "fp" {
				SubProgram "d3d11 " {
					"!!DX11PixelSM40
					//
					// Generated by Microsoft (R) D3D Shader Disassembler
					//
					//
					// Input signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_POSITION              0   xyzw        0      POS   float       
					// COLOR                    0   xyzw        1     NONE   float      w
					// TEXCOORD                 0   xy          2     NONE   float   xy  
					// TEXCOORD                 1   xyzw        3     NONE   float   xyzw
					//
					//
					// Output signature:
					//
					// Name                 Index   Mask Register SysValue  Format   Used
					// -------------------- ----- ------ -------- -------- ------- ------
					// SV_Target                0   xyzw        0   TARGET   float   xyzw
					//
					ps_4_0
					dcl_constantbuffer CB0[4], immediateIndexed
					dcl_sampler s0, mode_default
					dcl_resource_texture2d (float,float,float,float) t0
					dcl_input_ps linear v1.w
					dcl_input_ps linear v2.xy
					dcl_input_ps linear v3.xyzw
					dcl_output o0.xyzw
					dcl_temps 1
					sample r0.xyzw, v2.xyxx, t0.xyzw, s0
					mad r0.x, r0.w, v1.w, -cb0[3].x
					lt r0.x, r0.x, l(0.000000)
					discard_nz r0.x
					mov o0.xyzw, v3.xyzw
					ret 
					// Approximately 0 instruction slots used"
				}
			}
		}
	}
}